version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
        - "5432:5432"
    graphql-engine:
        image: hasura/graphql-engine:v1.0.0-alpha29
        ports:
        - "8090:8080"
        depends_on:
        - postgres
        environment:
        - "POSTGRES_PASSWORD:airflow"
        command: >
            /bin/sh -c "
            graphql-engine --database-url postgres://airflow:airflow@postgres:5432/airflow serve --enable-console;
            "
    webserver:
        image: puckel/docker-airflow:1.10.1
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./dags/requirements.txt:/requirements.txt
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
            - "5555:5555"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3s